name: Deploy to Elastic Beanstalk

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: Git Tag to be released
      aws-eb-app:
        description: 'AWS Elastic Beanstalk application'     
        required: true
        type: choice
        options:
        - products-demo
        - customer2
        - customer3
      aws-eb-environment:
        description: 'AWS Elastic Beanstalk environment'     
        required: true
        type: choice
        options:
        - Productsdemo-env
        - dev
        - stage
        - validation

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Update docker-compose.yml with correct tag/version
        run: sed -i 's/${DEMO_VERSION}/${{ inputs.tag }}/g;s/${SERVICE_PORT}/80/g' docker-compose.yml

      - run: cat docker-compose.yml

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          use_existing_version_if_available: false
          application_name: ${{ inputs.aws-eb-app }}
          environment_name: ${{ inputs.aws-eb-environment }}
          version_label: ${{github.SHA}}
          region: eu-central-1
          deployment_package: docker-compose.yml
