name: Deploy to Elastic Beanstalk

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: Git Tag to be released

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Update Dockerrun.aws.json with correct tag/version
        uses: jossef/action-set-json-field@v2
        with:
          file: Dockerrun.aws.json
          field: Image.Name
          value: sulhina/products-demo:${{ inputs.tag }}
      
      - run: cat Dockerrun.aws.json

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          use_existing_version_if_available: false
          application_name: products-demo
          environment_name: Productsdemo-env
          version_label: ${{github.SHA}}
          region: eu-central-1
          deployment_package: Dockerrun.aws.json
